import { Sora, Poppins } from "next/font/google";
import "./globals.css";

const sora = Sora({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-Sora",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "HackTO",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${sora.variable} ${poppins.variable}`}>
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{metadata.title}</title>
        <meta description={metadata.description} />
      </head>
      <body>{children}</body>
    </html>
  );
}
